modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory. 26 for 1.14.2, 27 for 1.14.3
[[mods]] #mandatory
modId="adrigorithm" #mandatory
version="1.0" #mandatory
displayName="Adrigorithm" #mandatory
description='''
Adri's first mod!
'''